# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'Demo' do
  use_frameworks!
  # Pods for Demo
  pod 'RMHttp', :path => '../'
  
  target 'DemoTests' do
      inherit! :search_paths
      pod 'RMHttp', :path => '../'
  end
end

#target 'DemoTests' do
#   use_frameworks!
#   # Pods for testing
#   pod 'RMHttp', :path => '../'
#end
